name: tasklite
version: 0.1.0.0
github: "ad-si/tasklite"
license: ISC
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: CLI task / todo list manager with SQLite backend
category: Cli

description: |
  Please see the README on GitHub
  at <https://github.com/ad-si/tasklite#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - beam-core
  - beam-sqlite
  - bytestring
  - cassava
  - crockford
  - directory
  - fuzzy
  - hourglass
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - protolude
  - sqlite-simple
  - text
  - ulid
  - yaml

default-extensions:
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - UndecidableInstances


library:
  source-dirs: source

executables:
  tasklite:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -fno-warn-orphans
    dependencies:
      - tasklite

tests:
  tasklite-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - tasklite
