resolver: lts-16.14
packages:
  - huzzy
  - tasklite-core
  - tasklite-server
  # - tasklite-api
  # - tasklite-app
  # - tasklite-web

extra-deps:
  - github: haskell-beam/beam
    # 2020-09-09
    commit: ef3a4e6ce67edc145b7877cd9942168c97d43dcf
    subdirs:
      - beam-core
      - beam-migrate
      - beam-sqlite
  - sqlite-simple-0.4.18.0
  - acid-state-0.16.0.1
  - dependent-map-0.2.4.0
  - dependent-sum-0.5
  - direct-sqlite-2.3.26
  - iso8601-duration-0.1.1.0
  - portable-lines-0.1
  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
