resolver: lts-13.25
packages:
  # - tasklite-api
  - tasklite-app
  - tasklite-core
  # - tasklite-web

extra-deps:
  - beam-sqlite-0.4.0.0
  - beam-core-0.8.0.0
  - beam-migrate-0.4.0.1
  - crockford-0.2
  - fuzzy-0.1.0.0
  - gi-gtk-declarative-0.4.2
  - gi-gtk-declarative-app-simple-0.4.1
  - ulid-0.2.0.0
  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
image:
  containers:
    - base: haskell-datasette
      name: adius/tasklite
      entrypoints:
        - tasklite
