name: tasklite-core
version: 0.3.0.0
github: "ad-si/tasklite"
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber

extra-source-files:
  - README.md

data-files:
  - example-config.yaml

synopsis: CLI task / todo list manager with SQLite backend
category: CLI, Task, Todo

description: |
  Please see the README on GitHub
  at <https://github.com/ad-si/tasklite#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - beam-core
  - beam-migrate
  - beam-sqlite
  - bytestring
  - cassava
  - directory
  - file-embed
  - filepath
  - generic-random
  - githash
  - hourglass
  - hsemail
  - huzzy
  - optparse-applicative
  - parsec
  - portable-lines
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - protolude
  - QuickCheck
  - quickcheck-instances
  - read-editor
  - simple-sql-parser
  - sqlite-simple
  - text
  - time
  - ulid
  - unix
  - unordered-containers
  - vector
  - yaml

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - UndecidableInstances

ghc-options:
  - -fno-warn-orphans
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  # - -Wunused-packages

library:
  source-dirs: source

executables:
  tasklite:
    main: Main.hs
    source-dirs: app
    dependencies:
      - tasklite-core

tests:
  tasklite-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - tasklite-core
      - temporary

benchmarks:
  tasklite-bench:
    main: Main.hs
    source-dirs: benchmarks
    dependencies:
      - criterion
      - tasklite-core
