resolver: lts-14.27
packages:
  - huzzy
  - tasklite-core
  # - tasklite-api
  # - tasklite-app
  # - tasklite-web

extra-deps:
  - gi-gtk-declarative-0.4.2
  - gi-gtk-declarative-app-simple-0.4.1
  - iso8601-duration-0.1.1.0
  - portable-lines-0.1
  - ulid-0.3.0.0
  - github: JakeWheat/simple-sql-parser
    commit: 00433a26e8303c9e61359f406da5a2dbf1293fc8

allow-newer: true

# Build TaskLite in a container
# docker:
#   repo: fpco/stack-build

# Copy executable to new image
# image:
#   containers:
#     - base: haskell-datasette
#       name: adius/tasklite
#       entrypoints:
#         - tasklite
