name: Haskell Stack CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Install dependencies
        run: stack install tasklite-core

      - name: Build
        run: stack build tasklite-core

      - name: Set env with output of `git describe`
        run: echo ::set-env name=GIT_DESCRIBE::$(git describe --tags)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GIT_DESCRIBE }}
          release_name: Release ${{ env.GIT_DESCRIBE }}
          body: ${{ github.event.commits[0].message }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/.local/bin/tasklite
          asset_name: tasklite
          asset_content_type: application/octet-stream
